### ISSUE TITLE
ValueError: could not broadcast input array from shape (185,219,150) into shape (185,219,0)

### ISSUE THREAD

**Issue by alenchen-0606** [vanandrew/brainextractor#1]
Hello, thanks for your good repository.

When i adjust the threshold lower than 0.5 (ex: 0.2, 0.3), it's not work.
For the same image, threshold =0.5 is  work.

![error](https://user-images.githubusercontent.com/85331604/132481374-7b44f673-0213-45db-b6fe-498aa5fd5483.jpg)

**Comment by vanandrew** [comment]
@alenchen-0606 Glad you find this useful!

Need a little more information from you to debug this, but at first glance, it seems like the `bounds` property on the [VoxelGrid](https://trimsh.org/trimesh.voxel.html#trimesh.voxel.VoxelGrid) object is not reporting the correct extent of the volume data. 

Basically, what is happening in this part of the code is that after a surface boundary has been found for the brain (and stored at `self.surface`), we invoke the [`voxelized`](https://trimsh.org/trimesh.html?highlight=trimesh#trimesh.Trimesh.voxelized) method of the [`Trimesh`](https://trimsh.org/trimesh.html?highlight=trimesh#trimesh.Trimesh) object to go from a surface to a volume (in which `vol` is a [VoxelGrid](https://trimsh.org/trimesh.voxel.html#trimesh.voxel.VoxelGrid) object). Then we [`fill`](https://trimsh.org/trimesh.voxel.html#trimesh.voxel.VoxelGrid.fill) our volumized surface to get the mask. Since the original brain volume data generally doesn't extend across the entire extent of the original image, we need to find where to "insert" the volume data. This is so when we save out the mask, it actually lines up with the original image.

In [brainextractor/main.py line 400-411](https://github.com/vanandrew/brainextractor/blob/83d9be553ddcbc2a0dea6b6bd55e8eb6d48f6c2b/brainextractor/main.py#L400-L411), could you add the following line and rerun:

```python
    def compute_mask(self):
        """
            Convert surface mesh to volume
        """
        vol = self.surface.voxelized(1)
        vol = vol.fill()
        print(vol.bounds)  # <-- ***Add me!***
        self.mask = np.zeros(self.shape)
        self.mask[
            int(vol.bounds[0,0]):int(vol.bounds[1,0]),
            int(vol.bounds[0,1]):int(vol.bounds[1,1]),
            int(vol.bounds[0,2]):int(vol.bounds[1,2])] = vol.matrix
        return self.mask
```
It should print out a 2 x 3 `numpy` array with what `trimesh` thinks the bounds of the volume are. If it's reporting something weird, then we can go from there.

Also what version of `trimesh` do you have installed?

**Comment by alenchen-0606** [comment]
Thanks for your quick reply.

Rerun as you request, it return [[ 26.5   5.5  -1.5] [211.5 224.5 148.5]].
It's weird that the vol.bounds[0,2] is negative.
It make self.mask.shape = [185, 219, 0]

My trimesh version = 3.9.29, and i also try 3.8.15.

**Comment by vanandrew** [comment]
Ah, there's our problem. The negative bound is definitely weird, so I wonder if I've just been off 1 voxel when generating the mask this entire time...

Will investigate and try to push a fix by the end of this week. Thanks for finding this issue!

**Comment by alenchen-0606** [comment]
Thank you a lot!!

**Comment by vanandrew** [comment]
@alenchen-0606 Would it be possible for you to attach the file you are running this on? Would make it much easier for me to debug this.

**Comment by vanandrew** [comment]
Thanks for sending me that file. I've pushed commit 10b8139 which should hopefully fix the issue.

Let me know if you have any more problems.

**Comment by RiaanZoetmulder** [comment]
Hello vanandrew,

Unfortunately, i seem to be running into the same issue even with the fix. I have modified the brain extractor to work on CT head scans (FI is now 0.01). That is pretty much the only thing I have changed.

The error specifically is:

ValueError: could not broadcast input array from shape (390,489,322) into shape (390,489,340)

So the issue seems to really be with the final dimension.

Kind regards,


Riaan Zoetmulder

**Comment by vanandrew** [comment]
@RiaanZoetmulder Can you post the output after adding this line to the code?

    400    def compute_mask(self):
    401           """
    402               Convert surface mesh to volume
    403           """
    404           vol = self.surface.voxelized(1)
    405           vol = vol.fill()
    406           print(vol.bounds)  # <-- ***Add me!***
    407           self.mask = np.zeros(self.shape)

It should report the original bounds of the mask that is found for the finialized surface.

**Comment by RiaanZoetmulder** [comment]
Certainly, I got this array:

[[ 57.5  10.5 -18.5]
 [447.5 499.5 339.5]]

**Comment by RiaanZoetmulder** [comment]
If it is relevant these are the steps for what I have done exactly:


1. clamp HU values between 0 and 100

2.  smoothing using a gaussian kernel

3.  clamp HU values again

4. Brain extraction

5. bug happens when I compute the mask.

**Comment by vanandrew** [comment]
I think I see the issue. There's definitely some errors with the way I'm computing the bounds for this edge case.

I'll push a fix for this soon, but I would recommend reexamining what you set for the `fractional_threshold` parameter. The fact that the bounds you are getting means that the surface being generated is extending past the extent of the image, which probably means that the algorithm couldn't find the brain surface.

My understanding is that this algorithm was written with T1w MR images in mind, so I'm not entirely sure how well it will work on CT images, but I would try a higher `fractional_threshold` than what you are currently using.

**Comment by RiaanZoetmulder** [comment]
Hello,

Thank you for taking the time to look into this. There was recently a paper
that showed that with the right preprocessing steps BET can also work for
CT images, this is why I am trying it.

I have run the algorithm at a variety of fractional_threshold values, the
same error occurs.

Kind regards,

Riaan Zoetmulder

Op do 27 jan. 2022 om 16:42 schreef Andrew Van ***@***.***>:

**Comment by vanandrew** [comment]
@RiaanZoetmulder Hopefully this commit fixes your issue: fcbe718fab890f0538b2628db0cdd9284a78c6c3
Let me know if you still encounter an error.

**Comment by RiaanZoetmulder** [comment]
Hello,

It works now! And I also got it to work with CT!

Thank you for your help and quick reply,  I appreciate it. 

Kind regards,

Riaan Zoetmulder

**Comment by vanandrew** [comment]
@RiaanZoetmulder Awesome. Glad it works for you.
