### ISSUE TITLE
Is it implemented by functions such as BET2? And I see the following functions in FSL.

### ISSUE THREAD

**Issue by xingyunjohn1** [vanandrew/brainextractor#7]
![image](https://github.com/vanandrew/brainextractor/assets/32031270/944ac7a8-20f4-40dd-a4a7-f45ebd45e50e)

**Comment by vanandrew** [comment]
I'm not entirely sure what you're asking...

This project is a re-implementation of FSL's `bet` algorithm in Python. I wrote it for a class project and made it publicly available for reference.

It's not affiliated with the FSL project in any way.

**Comment by xingyunjohn1** [comment]
I am sorry for my bad expression.


1. I wonder whether there would be a `bet2` reimplementation in your project.
2. Accroding to the [intro of BET page](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BET), it seems `bet` should be used for *deleting non-brain tissue from an image of the whole head* while `bet2` should be used for *skull and scalp surface extraction*. But accroding to the screenshot of the FSL software I showed above, brain extaction also uses `bet2`. I haven't research deep inside this. I would appriciate it if you kown something about this and tell me more about this.
3. Could you please tell me how many iterations that the FSL software runs while you set it for 1000 if you know?


At last, thank you for your great work of this reimplementation.

**Comment by vanandrew** [comment]
1. This project implements just `bet` (per the original paper: Smith SM. Fast robust automated brain extraction. Hum Brain Mapp. 2002 Nov;17(3):143-55. doi: 10.1002/hbm.10062. PMID: 12391568; PMCID: PMC6871816.). Features in `bet2` are not implemented and won't ever be implemented at this point.
2. Both `bet` and `bet2` will delete non-brain tissue from the image. My understanding is that `bet2` is mainly an extension on `bet` that includes _skull and scalp surface extraction_, it still uses the same underlying algorithm as `bet` for brain extraction.
3. I'm not entirely sure how many iterations is run in the FSL software's `bet`. When writing this, I only used the original paper as a guide and I did not look into any of FSL's `bet` source code. I chose 1000 iterations because I didn't see much change in the brain extraction results beyond that point (and 1000 seemed like a nice round number).

Hope this helps,
Andrew
